// quiz
export const GET_ALL_QUIZZES = 'GET_ALL_QUIZZES';
export const CREATE_QUIZ = 'CREATE_QUIZ';
export const UPDATE_QUIZ = 'UPDATE_QUIZ';
export const DELETE_QUIZ = 'DELETE_QUIZ';

// level
export const GET_ALL_LEVELS = 'GET_ALL_LEVELS';
export const CREATE_LEVEL = 'CREATE_LEVEL';
export const UPDATE_LEVEL = 'UPDATE_LEVEL';
export const DELETE_LEVEL = 'DELETE_LEVEL';

// app
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
export const UPDATE_REMAIN_TIME = 'UPDATE_REMAIN_TIME';
export const UPDATE_GAINED_SCORE = 'UPDATE_GAINED_SCORE';
export const UPDATE_GAINED_HINT = 'UPDATE_GAINED_HINT';
export const UPDATE_PLAYING_LEVEL = 'UPDATE_PLAYING_LEVEL';
export const UPDATE_LEVEL_TOTAL = 'UPDATE_LEVEL_TOTAL';

// user
export const GET_USER = 'GET_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_LANG = 'UPDATE_USER_LANG';
export const UPDATE_USER_LEVEL = 'UPDATE_USER_LEVEL';
export const UPDATE_USER_SCORE = 'UPDATE_USER_SCORE';
export const UPDATE_USER_HINT = 'UPDATE_USER_HINT';
export const UPDATE_USER_QUIZZES = 'UPDATE_USER_QUIZZES';
